# Generated by Django 6.0 on 2025-12-30 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Due_Date', models.DateField()),
                ('Status', models.CharField(choices=[('NEW', 'חדש'), ('IN_PROGRESS', 'בתהליך'), ('COMPLETED', 'הושלם')])),
                ('AssignedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'מנהל'), ('EMPLOYEE', 'עובד')])),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagementApp.teams', verbose_name='Team')),
            ],
        ),
    ]
