# Generated by Django 6.0 on 2025-12-30 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Teams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManagementApp.teams'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'מנהל'), ('EMPLOYEE', 'עובד')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.CharField(choices=[('NEW', 'חדש'), ('IN_PROGRESS', 'בתהליך'), ('COMPLETED', 'הושלם')], max_length=20),
        ),
    ]
