# Generated by Django 6.0 on 2025-12-30 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagementApp', '0004_alter_task_assigneduser_alter_task_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Teams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagementApp.teams'),
        ),
    ]
