# Generated by Django 6.0 on 2025-12-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagementApp', '0005_alter_task_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.CharField(choices=[('NEW', 'חדש'), ('IN_PROGRESS', 'בתהליך'), ('COMPLETED', 'הושלם')], default='NEW', max_length=20),
        ),
    ]
