# Generated by Django 6.0 on 2025-12-30 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagementApp', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'מנהל'), ('EMPLOYEE', 'עובד')], default='EMPLOYEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManagementApp.teams', verbose_name='Team'),
        ),
    ]
